version: "3"

services:
  db:
    image: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    volumes:
      - ../datadir:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 43hb34jhbt3o4bt3o4hbt3o4bt
      MYSQL_DATABASE: asi-share
  server:
    image: node:latest
    volumes:
      - ./:/app
    working_dir: /app
    restart: always
    ports:
      - 6000:6000
    command: node src/index.js
    env_file: ./.env
